# http://module-build.sourceforge.net/META-spec.html
name:         Hash-Extract
version:      0.01
version_from: lib/Hash/Extract.pm
installdirs:  site
author:       YAMASHINA Hio <hio@cpan.org>
abstract: extract hash values onto lexical variables.
license: perl
requires:
  Test::More: 0
build_requires:
  PadWalker: 0
no_index:
  directory:
    - inc
    - t

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.07, EUMM-6.17.
meta-spec:
  version: 1.2
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
